# Generated by Django 4.1.2 on 2023-03-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_year',
            field=models.DateField(default=2023, verbose_name='fecha de comprobante'),
        ),
    ]
