# Generated by Django 4.1.2 on 2023-03-20 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_inscription_date_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='date_year',
            field=models.CharField(blank=True, default=2023, max_length=4, verbose_name='año'),
        ),
    ]
