# Generated by Django 4.1.2 on 2023-03-22 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_inscription_date_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='cargo_tipo',
            field=models.CharField(choices=[('Matricula', 'Matricula'), ('Mensualidad', 'Mensualidad'), ('Diploma o Certificado', 'Diploma o Certificado')], default='Seleccione un nivel', max_length=30, verbose_name='Tipo de cargo'),
        ),
    ]
