# Generated by Django 4.1.2 on 2023-03-23 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_pago_cargo_tipo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='sexo',
            field=models.CharField(blank=True, choices=[('Masculino', 'M'), ('Femenino', 'F')], max_length=10, verbose_name='sexo'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='curso',
            field=models.CharField(choices=[('Primer Ciclo', 'Primer Ciclo'), ('Ciencias', 'Ciencias'), ('Comercio', 'Comercio'), ('Humanidades', 'Humanidades'), ('Informática', 'Informática'), ('Turismo', 'Turismo')], default='Seleccione un Curso', max_length=30, verbose_name='Curso'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='curso_nivel',
            field=models.CharField(choices=[('7mo', 'Séptimo grado'), ('8vo', 'Octavo grado'), ('9no', 'Noveno grado'), ('10mo', 'Décimo grado'), ('11mo', 'Undécimo grado'), ('12mo', 'Duodecimo grado')], default='Seleccione un nivel', max_length=30, verbose_name='nivel del curso'),
        ),
        migrations.AlterField(
            model_name='inscription',
            name='trimestre',
            field=models.CharField(choices=[('Primer Trimestre', 'I'), ('Segundo Trimestre', 'II'), ('Tercer Trimestre', 'III')], default='Opciones', max_length=30, verbose_name='trimestre'),
        ),
    ]
