# Generated by Django 4.1.2 on 2023-03-23 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_estudiante_sexo_alter_inscription_curso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inscription',
            name='trimestre',
            field=models.CharField(choices=[('I', 'Primer Trimestre'), ('II', 'Segundo Trimestre'), ('III', 'Tercer Trimestre')], default='Opciones', max_length=30, verbose_name='trimestre'),
        ),
        migrations.AlterField(
            model_name='pago',
            name='fk_inscription',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='app.inscription', verbose_name='comprobante de matricula'),
        ),
    ]
